export const environment = {
  production: true,
  apiUrl: 'api/',
  tuitionId: 1,
  nextYearTuitionId: 2,
  studentTypeId: 1,
  teacherTypeId: 2,
  parentTypeId: 3,
  adminTypeId: 4,
  absenceType: 1,
  lateType: 2,
  schoolServiceId: 1,
  maxChildNumber: 6,
  byDeadLineTypeId: true,
  orderCreated: 0,
  orderValidated: 1,
  orderExpired: 2,
  orderCancelled: 3,
  orderPaid: 4,
  orderOverdue: 5,
  orderCompleted: 6
};
