export const environment = {
  production: true,
  apiUrl: 'api/',
  tuitionId: 1,
  nextYearTuitionId: 2,
  studentTypeId: 1,
  teacherTypeId: 2,
  parentTypeId: 3,
  adminTypeId: 4,
  absenceType: 1,
  lateType: 2,
  schoolServiceId: 1,
  maxChildNumber: 6,
  byDeadLineTypeId: true,
  payCash: 1,
  payCheque: 2,
  payWire: 3,
  payMobile: 4,
  finOpTypeInvoice: 1,
  finOpTypePayment: 2
};
